name: Update blog posts

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: gautamkrishnar/blog-post-workflow@f177491c77670f150ab4e9b9890254d8eba4164b # v1
        with:
          feed_list: "https://k-o.pro/rss.xml"
          max_post_count: 4
          template: "• [$title]($url) - $date<br>"
          date_format: "mmm dd, yyyy"
